import type { Metadata } from "next";
import I18nProvider from './features/I18nProvider';
import { Locale, locales, initI18next } from '../i18n';
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;
  const i18n = await initI18next(locale, ['translation']);
  const resources = {
    [locale]: {
      translation: i18n.getResourceBundle(locale, 'translation'),
    },
  };
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider locale={locale} resources={resources}>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
